/* ------ COVID ONTOLOGY --------- */
DELETE FROM act_covid where sourcesystem_cd = 'wakehealth';

/* Diagnoses ICD-10 */
-- Insert into act_covid (C_HLEVEL,C_FULLNAME,C_NAME,C_SYNONYM_CD,C_VISUALATTRIBUTES,C_TOTALNUM,C_BASECODE,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE,C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,SOURCESYSTEM_CD,VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL)
-- SELECT C_HLEVEL+1, C_FULLNAME || 'x\',C_NAME,C_SYNONYM_CD,REPLACE(C_VISUALATTRIBUTES,'A','H'),C_TOTALNUM,REPLACE(C_BASECODE,'ICD10CM:','ICD10:'),C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE || 'x\',C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,'wakehealth' AS SOURCESYSTEM_CD,VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL FROM act_covid WHERE C_BASECODE IS NOT NULL AND C_BASECODE LIKE 'ICD10CM%';

update act_covid
SET 
    c_basecode = replace(c_basecode,'ICD10M:','ICD10:') 
    ,update_date = sysdate
where 
    c_basecode is not null and c_basecode like 'ICD10CM%'
;


/* Labs */
-- Insert into act_covid (C_HLEVEL,C_FULLNAME,C_NAME,C_SYNONYM_CD,C_VISUALATTRIBUTES,C_TOTALNUM,C_BASECODE,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE,C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,SOURCESYSTEM_CD,VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL)
-- SELECT C_HLEVEL+1, C_FULLNAME || 'x\',C_NAME,C_SYNONYM_CD,REPLACE(C_VISUALATTRIBUTES,'A','H'),C_TOTALNUM,REPLACE(C_BASECODE,'LOINC:','LOI|'),C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE || 'x\',C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,'wakehealth',VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL FROM act_covid WHERE C_BASECODE IS NOT NULL AND C_BASECODE LIKE 'LOINC%' and instr(c_basecode,' ') = 0;

update act_covid
set c_basecode = replace(c_basecode,'LOINC:','LOI|')
    ,update_date = sysdate
WHERE
    c_basecode is not null and c_basecode like 'LOINC:%'
;

/* Medications RXNORM */
Insert into act_covid (C_HLEVEL,C_FULLNAME,C_NAME,C_SYNONYM_CD,C_VISUALATTRIBUTES,C_TOTALNUM,C_BASECODE,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE,C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,SOURCESYSTEM_CD,VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL)
SELECT C_HLEVEL+1, C_FULLNAME || mapped.medication_id || '\',C_NAME,C_SYNONYM_CD,REPLACE(C_VISUALATTRIBUTES,'A','H'),C_TOTALNUM,'MEDID:' || mapped.medication_id,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE || mapped.medication_id || '\',C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,'wakehealth',VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL 
FROM act_covid ont
    JOIN (select distinct mcode, msystem, medication_id FROM map_medid@I2B2STAGE) mapped ON mapped.mcode = SUBSTR(ont.c_basecode,8) AND mapped.msystem like 'RXNORM%'
WHERE ont.c_basecode is not null and ont.c_basecode like 'RXNORM%';

/* Medicationss NDC */
Insert into act_covid (C_HLEVEL,C_FULLNAME,C_NAME,C_SYNONYM_CD,C_VISUALATTRIBUTES,C_TOTALNUM,C_BASECODE,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE,C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,SOURCESYSTEM_CD,VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL)
SELECT C_HLEVEL+1, C_FULLNAME || mapped.medication_id || '\',C_NAME,C_SYNONYM_CD,REPLACE(C_VISUALATTRIBUTES,'A','H'),C_TOTALNUM,'MEDID:' || mapped.medication_id,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE || mapped.medication_id || '\',C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,'wakehealth',VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL 
FROM act_covid ont
    JOIN (select distinct mcode, msystem, medication_id FROM map_medid@I2B2STAGE) mapped ON mapped.mcode = substr(ont.c_basecode,instr(ont.c_basecode,':')+1) AND mapped.msystem like 'NDC11%'
WHERE ont.c_basecode is not null and ont.c_basecode like 'NDC%';

/* Procedures ICD10PCS */
Insert into act_covid (C_HLEVEL,C_FULLNAME,C_NAME,C_SYNONYM_CD,C_VISUALATTRIBUTES,C_TOTALNUM,C_BASECODE,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE,C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,SOURCESYSTEM_CD,VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL)
SELECT C_HLEVEL+1, C_FULLNAME || mapped.source_code || '\',C_NAME,C_SYNONYM_CD,REPLACE(C_VISUALATTRIBUTES,'A','H'),C_TOTALNUM,'PXID:' || mapped.source_code,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE || mapped.source_code || '\',C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,'wakehealth',VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL 
FROM act_covid ont
    JOIN (select distinct mcode, msystem, source_code, source_system FROM map_procedures@I2B2STAGE) mapped ON mapped.mcode = substr(ont.c_basecode,instr(ont.c_basecode,':')+1) AND mapped.msystem like 'ICD-10-PCS%' AND mapped.source_system = 'PXID'
WHERE ont.c_basecode is not null and ont.c_basecode like 'ICD10PCS%'
;

/* Procedures HCPCS */
Insert into act_covid (C_HLEVEL,C_FULLNAME,C_NAME,C_SYNONYM_CD,C_VISUALATTRIBUTES,C_TOTALNUM,C_BASECODE,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE,C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,SOURCESYSTEM_CD,VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL)
SELECT C_HLEVEL+1, C_FULLNAME || mapped.source_code || '\',C_NAME,C_SYNONYM_CD,REPLACE(C_VISUALATTRIBUTES,'A','H'),C_TOTALNUM,'PROCID:' || mapped.source_code,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE || mapped.source_code || '\',C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,'wakehealth',VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL 
FROM act_covid ont
    JOIN (select distinct mcode, msystem, source_code, source_system FROM map_procedures@I2B2STAGE) mapped ON mapped.mcode = substr(ont.c_basecode,instr(ont.c_basecode,':')+1) AND mapped.msystem like 'HCPCS.2%' AND mapped.source_system = 'PROCID'
WHERE ont.c_basecode is not null and ont.c_basecode like 'HCPCS%'
;

/* Procedures CPT-4 */
Insert into act_covid (C_HLEVEL,C_FULLNAME,C_NAME,C_SYNONYM_CD,C_VISUALATTRIBUTES,C_TOTALNUM,C_BASECODE,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE,C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,SOURCESYSTEM_CD,VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL)
SELECT C_HLEVEL+1, C_FULLNAME || mapped.source_code || '\',C_NAME,C_SYNONYM_CD,REPLACE(C_VISUALATTRIBUTES,'A','H'),C_TOTALNUM,'PROCID:' || mapped.source_code,C_METADATAXML,C_FACTTABLECOLUMN,C_TABLENAME,C_COLUMNNAME,C_COLUMNDATATYPE,C_OPERATOR,C_DIMCODE || mapped.source_code || '\',C_COMMENT,C_TOOLTIP,M_APPLIED_PATH,UPDATE_DATE,DOWNLOAD_DATE,IMPORT_DATE,'wakehealth',VALUETYPE_CD,M_EXCLUSION_CD,C_PATH,C_SYMBOL 
FROM act_covid ont
    JOIN (select distinct mcode, msystem, source_code, source_system FROM map_procedures@I2B2STAGE) mapped ON mapped.mcode = substr(ont.c_basecode,instr(ont.c_basecode,':')+1) AND mapped.msystem like 'CPT-4%' AND mapped.source_system = 'PROCID'
WHERE ont.c_basecode is not null and ont.c_basecode like 'CPT4%'
;

/* Vital */
Update act_covid SET C_FACTTABLECOLUMN = 'patient_num', C_TABLENAME = 'patient_dimension', C_COLUMNNAME = 'vital_status_cd', C_OPERATOR = 'IN', C_DIMCODE = '''Y'',''D''' WHERE C_BASECODE = 'DEM|VITAL STATUS:D' AND C_VISUALATTRIBUTES LIKE '%L%';

/* Visit */
Update act_covid SET C_OPERATOR = 'IN', C_DIMCODE = '''I'',''IP''' WHERE lower(c_columnname) = 'inout_cd' AND C_BASECODE = 'I';
Update act_covid SET C_OPERATOR = 'IN', C_DIMCODE = '''O'',''OP''' WHERE lower(c_columnname) = 'inout_cd' AND C_BASECODE = 'O';


/* You must merge these changes into the crc concept dimension tables after making updates */